name: Build and Release CPU/GPU Miner

on:
  push:
    branches:
      - main

concurrency:
    group: ${{ github.repository }}-${{ github.event.ref }}
    cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up CUDA
      uses: Jimver/cuda-toolkit@v0.2.11
      id: cuda-toolkit
      with:
          cuda: 11.8.0

    - name: Create build directory
      run: mkdir build
      working-directory: ${{ github.workspace }}

    - name: Configure CMake
      run: |
        cd src/build
        cmake ..
      working-directory: ${{ github.workspace }}

    - name: Build CUDA code
      run: |
        cd src/build
        make -j$(nproc)
        chmod +x ./3dp-miner
        tar -czf 3dp-miner_ubuntu22.tar.gz ./3dp-miner
      working-directory: ${{ github.workspace }}

    
    - name: Create Release
      uses: ncipollo/release-action@v1.13.0
      with:
        artifacts: |
          src/build/3dp-miner_ubuntu22.tar.gz
        draft: true
        prerelease: false
        skipIfReleaseExists: true
        artifactErrorsFailBuild: true
        tag: latest-${{ github.event.ref }}
